spring:
  application:
    name: provider
  profiles:
    active: local

server:
  port: 3002

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka:1234@localhost:3000/eureka/

mybatis:
  mapper-locations: classpath*:mappings/*.xml
  type-aliases-package: com.forest.provider.entity
  configuration:
    map-underscore-to-camel-case: true
